plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.simplyopen.runa.scanner'
version = '0.1.0'

android {
  namespace "app.simplyopen.runa.scanner"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'io.legere:pdfiumandroid:1.0.32'
}
